labels:
  type: exec
  platform: linux/amd64

steps:
- name: build-docs
  image: bash
  commands:
  - make build
  - cd public && git init
  - |
    for download_url in $(curl -SsL $(curl -SsL https://api.github.com/repos/drycc/workflow-cli/releases|jq -r '.[0].assets_url') | jq -r '.[].browser_download_url'); do
      echo $(echo $download_url | sed s#https://github.com#https://drycc-mirrors.drycc.cc#g) >> workflow-cli.txt
    done
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry
  when:
    event:
    - tag
    - push
    - cron

- name: publish-docs
  image: bash
  commands:
  - chown -R root:root public
  - podman run --rm
      -e DRONE_COMMIT_AUTHOR="${CI_COMMIT_AUTHOR:-drycc}"
      -e DRONE_COMMIT_AUTHOR_EMAIL="${CI_COMMIT_AUTHOR_EMAIL:-team@drycc.cc}"
      -e PLUGIN_SSH_KEY="$SSH_DEPLOY_KEY"
      -e PLUGIN_BRANCH=main
      -e PLUGIN_REMOTE=git@github.com:drycc/www.drycc.cc.git
      -e PLUGIN_FORCE=true
      -e PLUGIN_COMMIT=true
      -e PLUGIN_PATH=public
      -e PLUGIN_COMMIT_MESSAGE="init repo"
      -v "$(pwd):$(pwd)"
      -w "$(pwd)"
      docker.io/appleboy/drone-git-push
  environment:
    SSH_DEPLOY_KEY:
      from_secret: ssh_deploy_key
  when:
    event:
    - tag
    - push
    - cron
